/* ================================================================
   Form field ID configuration
   ----------------------------------------------------------------
   This file is auto-generated by setup.html.
   Open setup.html in your browser, follow the steps, then copy
   the generated config and replace the FORM_CONFIG object below.
================================================================ */

const FORM_CONFIG = {
  entries: {
    // phone: 'entry.1234567890',
    // device: 'entry.1234567890',
    // ...
  }
};
