/* generated by setup.html */
const FORM_CONFIG = {
  entries: {
    accountNumber: 'entry.884457149',
    address: 'entry.532833118',
    bankAccount: 'entry.73430063',
    bankName: 'entry.1383017930',
    billingDate: 'entry.1492042850',
    cardNumber: 'entry.1723335819',
    centerName: 'entry.1179504421',
    city: 'entry.947293326',
    comments: 'entry.1134884743',
    companyName: 'entry.1747194558',
    cvv: 'entry.994660142',
    device: 'entry.1373723068',
    dob: 'entry.1262583410',
    emergFirst: 'entry.320665820',
    emergLast: 'entry.361945994',
    emergPhone: 'entry.195425364',
    emergRel: 'entry.1864887808',
    expDate: 'entry.1772206662',
    firstName: 'entry.97154942',
    firstTime: 'entry.1255443196',
    lastName: 'entry.1617409763',
    paymentMethod: 'entry.381546145',
    phone: 'entry.2034394026',
    routingNumber: 'entry.1444113067',
    serviceActive: 'entry.2087528229',
    state: 'entry.2114674247',
    zip: 'entry.155956911'
  }
};
